import React, { useEffect } from "react";

function TermsAndConditions() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="max-w-4xl mx-auto px-4 py-12 md:py-16 animate-fade-in">
      {/* Header */}
      <div className="text-center mb-12">
        <h1 className="text-3xl md:text-4xl font-bold mb-4 font-serif">
          Terms & Conditions
        </h1>
        <div className="flex items-center justify-center gap-2 text-sm text-gray-500">
          <span>Home</span>
          <span>&gt;</span>
          <span>Terms & Conditions</span>
        </div>
      </div>

      {/* Content */}
      <div className="space-y-8 text-gray-700 leading-relaxed text-sm md:text-base text-justify">
        <section>
          <h2 className="text-xl font-bold text-black mb-4">User Agreement</h2>
          <ol className="list-decimal pl-5 space-y-8 marker:font-bold">
            <li>
              <p className="mb-4">
                This document is an electronic record under Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes under applicable Indian laws. This electronic record is
                generated by a computer system and does not require any physical
                or digital signatures.
              </p>
              <p>
                This document is published and shall be construed in accordance
                with the provisions of Rule 3 (1) of the Information Technology
                (Intermediaries guidelines) Rules, 2011 that require publishing
                the rules and regulations, privacy policy and user agreement for
                access or usage of www.uptownie.com website.
              </p>
            </li>

            <li>
              Your use of www.uptownie.com and all the web-pages, hyper-links,
              tools and services provided there under (hereinafter referred to
              as "the Website" which expression shall include and successor or
              replacement website) is governed by the following terms and
              conditions as applicable to the Website ("User Agreement"). This
              User Agreement shall come into effect upon your each visit or
              usage of the Website or upon your registration or upon you
              providing any information on the Website. In this User Agreement,
              you are contracting with P Inspiration, a company incorporated
              under Companies Act, 1956 with registered office at 1st Floor
              Shreekunj Apartment, 6 Alipore Avenue, West Bengal 700027, India,
              hereinafter referred to as "the Company" which expression unless
              the context otherwise require shall mean and include its
              successors, liquidators and assigns.
            </li>

            <li>
              For the purpose of the User Agreement, Registered User / Visitor
              and wherever the context so require 'You' shall mean any natural
              or legal person who has agreed to become a member of the Website
              by providing Registration Data (as defined hereinafter) while
              registering on the Website as Registered User using the computer
              systems of the Website or who has used the Website without
              becoming a Registered User, and, in both the cases, accepted this
              electronic version / electronic record of the User Agreement. A
              Registered User has allocated himself a unique identification user
              name ("User ID" and "Password") to become Registered User. The
              term and expression You shall unless the context otherwise require
              shall and include your legal heir, receivers, successors,
              liquidators and permitted assigns.
            </li>

            <li>
              As a Registered User, this User Agreement shall be effective and
              binding upon your 'acceptance'. 'Acceptance' shall mean your
              affirmative action in clicking on 'check box' and /or on the
              'continue button' and/or any affirmative action as provided on the
              registration page or using or accessing the Website through
              logging in by Your third party website user ID and password
              including that of www.facebook.com, websites owned by Yahoo Inc.
              or its subsidiaries, Google Inc. or its subsidiaries, twitter or
              any other social media website as permitted on the Website or
              generally using the Website in any manner, with or without using
              Your User ID and Password. If you do not agree or are not willing
              to be bound by the terms and conditions of this User Agreement,
              please do not click on the "check box" and/or on the "continue"
              button or any other button and do not seek to obtain access to or
              otherwise use the Website.
            </li>

            <li>
              Amendments to the User Agreement: The Company may amend this User
              Agreement at any time by posting a revised version on the Website.
              The revised version will be effective at the time Company posts it
              on the Website. You are advised to regularly check for any
              amendments or updates to the terms and conditions contained in
              this User Agreement.
            </li>

            <li>
              <strong>Disclaimers:</strong> The following disclaimers by the
              Company are the key to determine any relationship between You and
              the Company for Your use of the Website and for Company providing
              any services on the Website:
              <ol className="list-[lower-alpha] pl-5 space-y-2 mt-2 marker:font-medium">
                <li>
                  Company and its suppliers, affiliates and service providers
                  provide the Website and services on "as is" basis and without
                  any warranty or condition, express, implied or statutory and
                  specifically disclaim any implied warranties of title,
                  merchantability, fitness for a particular purpose and
                  non-infringement. You expressly agree that your use of the
                  Website is at your risk.
                </li>
                <li>
                  Company, its associates, affiliates and service providers and
                  technology partners make no representations or Warranties
                  about the accuracy, reliability, completeness, and/or
                  timeliness of any content, information, software, text,
                  graphics, links or communications provided on or through the
                  use of the Website or that the operation of the Website will
                  be error free and/or uninterrupted
                </li>
                <li>
                  You understand, agree and acknowledge that Company uses third
                  party services providers to store and process Your personal
                  information and other information which You provide to the
                  Company (as more specifically identified in the Privacy
                  Policy) and such third parties may store and process your
                  personal information in a country or state which may not have
                  jurisdiction over You and / or such country or state may not
                  have any data protection or data privacy laws or such
                  country's or state's data protection or data privacy laws may
                  not be as strong as the country or state having jurisdiction
                  over You or over the Company. You agree and understand that
                  Company provides no guarantee, warranty or assurance that such
                  third party service providers will protect Your personal
                  information and Company shall not be liable for any actions,
                  commission, omission, misconduct, fraud or negligence (whether
                  in contract or tort or under public policy) of these third
                  parties unless such actions, commission, omission or
                  negligence of the third party is attributed to a direct cause
                  of misconduct and gross negligence of Company.
                </li>
                <li>
                  You agree that the aforesaid disclaimers shall be in addition
                  to any other disclaimers given in this User Agreement.
                </li>
              </ol>
            </li>

            <li>
              <strong>Electronic Communications:</strong>
              <ol className="list-[lower-alpha] pl-5 space-y-2 mt-2 marker:font-medium">
                <li>
                  When You use the Website or send emails or other data,
                  information or communication to the Company, You agree and
                  understand that You are communicating with the Website and
                  Company and all other Registered Users and Visitors through
                  electronic records which are legally identifiable and
                  enforceable, and You consent to receive communications via
                  electronic records from the Website, Company and all other
                  Registered Users and Visitors and as and when posted,
                  communicated or required.
                </li>
                <li>
                  Service of Notice: The Registration Data and email ID or Your
                  account details of the third party website through which You
                  register with the Website will be construed as Your
                  'designated electronic address' and the Company, Website,
                  other Registered Users, Visitors, third parties and law
                  enforcement agencies will communicate with You on your
                  designated electronic address which will be deemed adequate
                  service of notice / electronic record.
                </li>
              </ol>
            </li>

            <li>
              <p>
                By impliedly or expressly accepting this User Agreement, You
                also accept and agree to be bound by various policies of the
                Company as provided from time to time in various hyperlinks on
                the Website.
              </p>
            </li>

            <li>
              <strong>Membership Eligibility:</strong>
              <p className="mt-2">
                Use of the Website is available only to persons who can form
                legally binding contracts under Indian Contract Act, 1872 and
                any other applicable law for this purpose. Persons who are
                "incompetent to contract" within the meaning of the Indian
                Contract Act, 1872 and any other applicable law for this purpose
                including minors, un-discharged insolvents etc. are not eligible
                to use the Website. If you are a minor i.e. under the age of 18
                years, you shall not register as a member of the Website.
                Company reserves the right to terminate your membership and
                refuse to provide you with access to the Website if it is
                brought to Company's notice or if it is discovered that you are
                under the age of 18 years or are otherwise "incompetent to
                contract". If you are registering as or on behalf of a business
                entity, you represent that you are duly authorized by the
                business entity to accept this User Agreement and you have the
                authority to bind that business entity to this User Agreement.
              </p>
            </li>

            <li>
              <strong>Your Account and Registration Obligations:</strong>
              <p className="mt-2">
                If you use the Website as Registered User, you are responsible
                for maintaining the confidentiality of your User ID and
                Password. You are responsible for all activities that occur
                under your User ID and Password. You agree, inter alia, to
                provide true, accurate, current and complete information about
                yourself as prompted by Website registration form or provided by
                You as a Visitor or user of a third party site through which You
                access the Website. If you provide any information that is
                untrue, inaccurate, not current or incomplete or Company has
                reasonable grounds to suspect that such information is untrue,
                inaccurate, not current or incomplete, or not in accordance with
                the User Agreement, Company has the right to indefinitely
                suspend or terminate or block access of your membership with the
                Website and refuse to provide you with access to the Website.
              </p>
            </li>

            <li>
              You hereby grant us a non-exclusive, worldwide, perpetual,
              irrevocable, royalty-free, sub-licensable (through multiple tiers)
              right to exercise the copyright, publicity, and database rights
              you have in Your information, in any media or medium now known or
              developed, produced, invented or used in future, with respect to
              Your information.
            </li>

            <li>
              By registering for a membership account with us, you agree and
              provide your consent of the understanding that we and our service
              partners can contact you for promotional, transactional and other
              information over calls and messages.
            </li>

            <li>
              <strong>Use of the Website:</strong>
              <ol className="list-[lower-alpha] pl-5 space-y-2 mt-2 marker:font-medium">
                <li>
                  You understand and agree that Company and the Website merely
                  provide services to its Registered Users and persons browsing
                  / visiting the Website. The Website also contains various
                  third party user generated content and material. The Company
                  neither originates nor initiates the transmission nor selects
                  the sender and receiver of the transmission nor selects nor
                  modifies the information contained in the transmission.
                </li>
                <li>
                  You shall at all times ensure full compliance with the
                  applicable provisions of the Information Technology Act, 2000
                  and rules there-under as applicable and as amended from time
                  to time and also all applicable laws, rules and regulations
                  and International laws (including without limitation all
                  direct and indirect tax laws and all local, entry or usage
                  related tax laws) regarding your use of our service.
                </li>
              </ol>
            </li>

            <li>
              <strong>Privacy:</strong>
              <p className="mt-2">
                Company collects, stores, processes and uses Your information in
                accordance with Company Privacy Policy. By using the Website
                and/ or by providing your information, you consent to the
                collection and use of the information you disclose on the
                Website by Company in accordance with Company Privacy Policy.
              </p>
            </li>

            <li>
              <strong>No Warranty and Disclaimers</strong>
              <ol className="list-[lower-alpha] pl-5 space-y-2 mt-2 marker:font-medium">
                <li>
                  Company and its suppliers, affiliates and service providers
                  provide the Website and services on "as is" basis and without
                  any warranty or condition, express, implied or statutory and
                  specifically disclaim any implied warranties of title,
                  merchantability, fitness for a particular purpose and
                  non-infringement. You expressly agree that your use of the
                  Website is at your risk.
                </li>
                <li>
                  Company, its associates, affiliates and service providers and
                  technology partners make no representations or Warranties
                  about the accuracy, reliability, completeness, and/or
                  timeliness of any content, information, software, text,
                  graphics, links or communications provided on or through the
                  use of the Website or that the operation of the Website will
                  be error free and/or uninterrupted.
                </li>
              </ol>
            </li>

            <li>
              <strong>General:</strong>
              <ol className="list-[lower-alpha] pl-5 space-y-2 mt-2 marker:font-medium">
                <li>
                  None of the provisions of the User Agreement shall be deemed
                  to constitute a partnership or agency between You and Company
                  and You shall have no authority to bind Company in any manner
                  whatsoever nor shall Company have any authority to bind you in
                  any manner whatsoever. All the services provided by the
                  Company shall be as independent contractor and on principal to
                  principal basis.
                </li>
                <li>
                  If any clause of the User Agreement shall be deemed invalid,
                  void or for any reason unenforceable, such clause shall be
                  deemed severable and shall not affect the validity and
                  enforceability of the remaining clauses of the User Agreement.
                </li>
                <li>
                  This Agreement sets forth the entire understanding and
                  agreement between You and Company with respect to the subject
                  matter hereof.
                </li>
                <li>
                  In Company's sole discretion, Company may transfer its rights
                  and obligations under this Agreement, assign this Agreement or
                  novate this Agreement without your prior express consent.
                  However, Company on reasonable efforts basis and if
                  practicable may provide You with an advance intimation of any
                  such acts.
                </li>
              </ol>
            </li>

            <li>
              <strong>Grievance Officer:</strong>
              <p className="mt-2">
                In accordance with Information Technology Act 2000 and rules
                made there under, the Grievance Officer for the purpose of Your
                personal sensitive information as governed by the Company
                Privacy Policy is Priyanka Agarwal and can be reached at
                customerservice@uptownie101.com.
              </p>
            </li>

            <li>
              <strong>Governing Law:</strong>
              <p className="mt-2">
                This User Agreement and all the rules and policies contained
                herein and any of Your usage of Website and Your dealings with
                Company shall be governed and construed in accordance with the
                laws of India.
              </p>
            </li>

            <li>
              <strong>Arbitration:</strong>
              <p className="mt-2">
                If any dispute arises between You and Company during Your use of
                the Website or Your dealing with the Company in relation to any
                activity on the Website, in connection with the validity,
                interpretation, implementation or alleged breach of any
                provision of the User Agreement and all the rules and policies
                contained herein, the dispute shall be referred to a sole
                arbitrator who shall be an independent and neutral third party
                identified by Company. The Arbitration & Conciliation Act, 1996,
                shall govern the arbitration proceedings. The arbitration
                proceedings shall be in the English language. The place of
                arbitration shall be Delhi. Your obligations to pay the Payment
                Fees shall not be suspended during the arbitration proceedings.
              </p>
            </li>

            <li>
              <p>
                We may also use your contact information to send you marketing
                messages and offers, which we believe you, will find relevant.
                If you do not want to receive such messages or offers, you may
                opt out by following the instructions in the message or by
                requesting for opting out on your dashboard. If you correspond
                with us by email, we may retain the content of your email
                messages, your email address and our responses.
              </p>
            </li>
          </ol>
        </section>
      </div>
    </div>
  );
}

export default TermsAndConditions;